### ISSUE TITLE
Resolve indirect dependency to Ryan's previous-named package

### ISSUE THREAD

**Issue by ymtszw** [dillonkearns/elm-rss#5]
elm-rss depends on [dmy/elm-imf-date-time](https://github.com/dmy/elm-imf-date-time), which depends on `ryannhg/date-format`, causing [recently announced rename issue](https://discourse.elm-lang.org/t/ryannhg-packages-renamed-to-ryan-haskell/9705) on fresh environment (where old package archives are not cached). 

I have created upkeep PR on the upstream:
https://github.com/dmy/elm-imf-date-time/pull/1

If the above PR is merged, it would be nice if you can follow it up in this package, too 👍

**Comment by ymtszw** [comment]
In the meantime, I have devised a workaround: artificially caching `ryannhg/**` packages under `$ELM_HOME`
<https://github.com/ymtszw/ymtszw.github.io/blob/40e0e2c52ee8d4eaa4e9bfc4837e6bf0806d4064/script/artificially-cache-ryannhg-packages.sh#L1>

The cache tarball originates from my own local MacBook, which only contains `ryannhg/date-format/2.3.0/`, but works as long as it is the only requirement.

**Comment by dillonkearns** [comment]
Thank you @ymtszw! Yes, I hope that the upstream PR gets merged in soon there, and I will update and publish ASAP once there's an update there 👍  Thanks for the heads up!

**Comment by dillonkearns** [comment]
Hello! I saw that the PR was merged and published with [dmy/elm-imf-date-time 1.0.2](https://package.elm-lang.org/packages/dmy/elm-imf-date-time/1.0.2/).

Now I'm wondering, should I go ahead and bump the package version to have a minimum of 1.0.2?

So instead of 

```json

        "dmy/elm-imf-date-time": "1.0.1 <= v < 2.0.0",
```

It would be:
```json

        "dmy/elm-imf-date-time": "1.0.2 <= v < 2.0.0",
```

Or is it already fine for users with that version being published?

**Comment by ymtszw** [comment]
I think we should bump.

As I reported in the OP, versions depdending on old-name package are, although valid code-wise, basically not buildable in the fresh environment. Therefore we should "retire" such versions as effectively as we can go.

**Comment by dillonkearns** [comment]
Sounds good, thank you for talking through the change with me! Just pushed and kicking off a publish now.

**Comment by dillonkearns** [comment]
Published! https://package.elm-lang.org/packages/dillonkearns/elm-rss/2.0.4/

https://github.com/dillonkearns/elm-rss/blob/2.0.4/CHANGELOG.md#204---2024-04-02
